PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS VecPairs ( 
   id INTEGER PRIMARY KEY,
   R_F_str TEXT NOT NULL, 
   VA INTEGER NOT NULL, 
   VB INTEGER NOT NULL, 
   NumPNs INTEGER NOT NULL, 
   PUFDesign_id INTEGER NOT NULL,
   FOREIGN KEY (PUFDesign_id) REFERENCES PUFDesign(id) ON UPDATE CASCADE ON DELETE CASCADE
   );

CREATE UNIQUE INDEX VecPairs_VA_VB_PD_index ON VecPairs (VA, VB, PUFDesign_id);
CREATE UNIQUE INDEX VecPairs_ID_index ON VecPairs (ID);
