PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS TimingVals ( 
   id INTEGER PRIMARY KEY,
   VecPair INTEGER NOT NULL, 
   PO INTEGER NOT NULL, 
   Ave INTEGER NOT NULL, 
   TSig INTEGER NOT NULL,
   PUFInstance INTEGER NOT NULL,
   FOREIGN KEY (VecPair) REFERENCES VecPairs(id) ON UPDATE CASCADE ON DELETE CASCADE,
   FOREIGN KEY (PUFInstance) REFERENCES PUFInstance(id) ON UPDATE CASCADE ON DELETE CASCADE
   );

CREATE UNIQUE INDEX TimingVals_PUFInst_VecPair_PO_Ave_index ON TimingVals (PUFInstance, VecPair, PO, Ave);
CREATE UNIQUE INDEX TimingVals_ID_index ON TimingVals (ID);

